// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0tXiFZ4T8WP9clEA9KFJ6E9BVOE0pag',
    appId: '1:973824794779:web:d2c7aabd512ed2b398e63e',
    messagingSenderId: '973824794779',
    projectId: 'fisioapp-73d11',
    authDomain: 'fisioapp-73d11.firebaseapp.com',
    databaseURL: 'https://fisioapp-73d11-default-rtdb.firebaseio.com',
    storageBucket: 'fisioapp-73d11.appspot.com',
    measurementId: 'G-4YYNWZM2E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhn8di_4COO-ou7uIC3P88M6FEuQB8k0',
    appId: '1:973824794779:android:49052affd981568d98e63e',
    messagingSenderId: '973824794779',
    projectId: 'fisioapp-73d11',
    databaseURL: 'https://fisioapp-73d11-default-rtdb.firebaseio.com',
    storageBucket: 'fisioapp-73d11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJgFdrYfgwrScTvRLY-s006e14nNTICE',
    appId: '1:973824794779:ios:b9a10f34c55759a798e63e',
    messagingSenderId: '973824794779',
    projectId: 'fisioapp-73d11',
    databaseURL: 'https://fisioapp-73d11-default-rtdb.firebaseio.com',
    storageBucket: 'fisioapp-73d11.appspot.com',
    iosClientId: '973824794779-lbnmvbim3tl5it0m4pd6ul7ft27mhihg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fisio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjJgFdrYfgwrScTvRLY-s006e14nNTICE',
    appId: '1:973824794779:ios:b9a10f34c55759a798e63e',
    messagingSenderId: '973824794779',
    projectId: 'fisioapp-73d11',
    databaseURL: 'https://fisioapp-73d11-default-rtdb.firebaseio.com',
    storageBucket: 'fisioapp-73d11.appspot.com',
    iosClientId: '973824794779-lbnmvbim3tl5it0m4pd6ul7ft27mhihg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fisio',
  );
}
